- name: "Configure machine with git"
  hosts: default
  pre_tasks:
    - apt: name=gpg state=present
      become: true
  roles:
    - role: gitconfig-data
    - role: gitconfig
      gitconfig_destination: ~/.gitconfig.local
      gitconfig_configuration: "{{git_local_configuration}}"
    - role: gitconfig
      gitconfig_destination: ~/.gitconfig.work
      gitconfig_configuration: "{{git_work_configuration}}"
    - role: gitconfig
      gitconfig_destination: ~/.gitconfig.github
      gitconfig_configuration: "{{git_github_configuration}}"
