Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "which python || sudo apt -y install python"

  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
